### ISSUE TITLE
Diseñar tablas

### ISSUE THREAD

**Issue by anabel17gr** [contemporanica/bbdd#1]

**Comment by bernat13** [comment]
cuando el pull request se aprueba, ya se pone en done la tarea @anabel17gr , no hace falta que la pongas tu. además, así sabemos exactamente cuando una tarea está terminada.

**Comment by alemartagon** [comment]
Se tienen que cambiar las tablas, hay que añadirle los campos email y contraseña en la tabla compositor @anabel17gr @PaulaHidalgo1 @Caastan @RobertoRodriguezNunez

**Comment by PaulaHidalgo1** [comment]
Si, ahora lo subimos arreglado, gracias
